### ISSUE TITLE
Scraping with clustered RabbitMQ

### ISSUE THREAD

**Issue by shamil** [deadtrickster/prometheus_rabbitmq_exporter#11]
Hi,

As far as I understand, when running clustered RabbitMQ, by scraping individual node will return mostly same metrics for those that start with `rabbitmq_`. I guess this is due to stats are shared between nodes.

How would you recommend to scrape this? How will I know which shared which are individual per node?

For example:
- `rabbitmq_consumers` are per node
- `rabbitmq_exchange_messages_published_out_total` are shared

Thanks

**Comment by deadtrickster** [comment]
Hello,

First, let me quote Management plugin docs:

> Note on clustering
>
>The management plugin is aware of clusters. You can enable it on one or more nodes in a cluster, and see information pertaining to the entire cluster no matter which node you connect to.
>
>If you want to deploy cluster nodes which do not have the full management plugin enabled, you will still need to enable the rabbitmq-management-agent plugin on each node.

So all AMQP related stat should be cluster-wide (I just double-checked it btw).

The only node-specific stuff is 
 - Erlang VM stat;
 - Process exporter stat.

Since Prometheus implicitly adds `instance` label I don't add `node` label myself.

In short - 1 AMQP dashboard for entire cluster. 1 Template  dashboard for VM & Process stat.

PS
If you have cool dashboards already, please consider sharing.

**Comment by deadtrickster** [comment]
Closing, feel free to comment and/or reopen.
