### ISSUE TITLE
[Improvement] - Additional RabbitMQ metrics

### ISSUE THREAD

**Issue by atzezitman** [deadtrickster/prometheus_rabbitmq_exporter#15]
There are several queueinfoitems that are currently not available as metric. https://www.rabbitmq.com/man/rabbitmqctl.1.man.html

Personally I was specifically looking for head_message_timestamp. Monitoring this timestamp enables me to verify there is no excessive delay in the system.
This items returns a timestamp, but for comparison in prometheus, it would be way easier if the return value was the same as time() (returns the number of seconds since January 1, 1970 UTC).

**Comment by deadtrickster** [comment]
Hi,  

Do you know what else is missing? I might add it if I'm digging into this anyway.

**Comment by atzezitman** [comment]
I will make list.

**Comment by deadtrickster** [comment]
Cool, 
Name is (already) a label,

- [ ] durable. boolean
- [ ] auto_delete. boolean
- [ ] arguments. not sure how to represent
- [ ] policy. can be label?
- [ ] exclusive. boolean
- [ ] exclusive_consumer_tag. can be label?
- [ ] head_message_timestamp. gauge or untyped? what's the default value if not present?
- [ ] state. can be `running`, `{syncing, MC}`, and `down`. 
     - running - 0
     - down - -1
     - syncing - MC

Thoughts?

**Comment by atzezitman** [comment]
Unfortunately I don't have too much experience on this subject. I agree with:
- [ ] arguments. label
- [ ] policy. label
- [ ] exclusive_consumer_tag. label

I am not sure how to implement the default value for head_message_timestamp. I thought it would simply return no data. I guess a gauge can't represent NaN, so it probably needs to be untyped. Only I don't know if the binary operators will still be available.

Other types look correct.

**Comment by deadtrickster** [comment]
Pushed new release. New metrics:

rabbitmq_queue_durable
rabbitmq_queue_auto_delete
rabbitmq_queue_exclusive
rabbitmq_queue_head_message_timestamp
rabbitmq_queue_state - note that this is a gauge. down is N/A, running is 0. The idea is to be able to calculate sum of all messages in sync across all queues.

Labels are next

**Comment by sdwire** [comment]
What's the likelihood of expanding the scope of this request to include metrics for other properties from the head message?  Here's why I ask...

The timestamp of the head message is the best metric available to evaluate the entire system's ability to keep up with demand.  The Feb 11 release added `rabbitmq_queue_head_message_timestamp`, which tries to provide that metric -- assuming the `head_message_timestamp` property actually gets populated. Unfortunately, for messages smaller than `queue_index_embed_msgs_below` bytes, that property remains empty because the messages never go to the message store.

In our installation, practically all of the messages are tiny (even though processing each one takes a long time and queues tend to build up). Pushing them into the message store just to populate `head_message_timestamp` is too big a performance hit to take. That means that  prometheus_rabbitmq_exporter's `rabbitmq_queue_head_message_timestamp` metric is always blank.

There is, however, a different plugin (https://github.com/rabbitmq/rabbitmq-message-timestamp) that can use a different mechanism to populate a property without that performance hit. I'd like to be able to have the option to configure prometheus_rabbitmq_exporter to publish the `timestamp` or `timestamp_in_ms` property that the other plugin populates on the head message.

Anyway, that's the background of "why" behind the request to allow configurable properties to be added as custom metrics in the exporter. Is that something that fits this project's goals?

**Comment by deadtrickster** [comment]
Thanks for providing the background. 

Timestamp is one of the [basic class properties](https://www.rabbitmq.com/amqp-0-9-1-reference.html#class.basic) and `head_message_timestamp` property of queues populated for example, here [rabbitmq_variable_queue:head_message_timestamp](https://github.com/rabbitmq/rabbitmq-server/blob/e811e30fff3ff9170c8103d100e24b4c0469f5ff/src/rabbit_variable_queue.erl#L1048) which calls [rabbit_basic:extract_timestamp](https://github.com/rabbitmq/rabbitmq-server/blob/2115942b607ded3d75d9d6ebb93ee31ffacb5bc3/src/rabbit_basic.erl#L244).

`rabbitmq-message-timestamp` actually [populates the same property](https://github.com/rabbitmq/rabbitmq-message-timestamp/blob/master/src/rabbit_timestamp_interceptor.erl#L69) (if not set).

I would say it should just work. If it doesn't, perhaps other conditions aren't met. Or I miss something?

**Comment by sdwire** [comment]
Looks like I completely misunderstood what the rabbitmq-message-timestamp plugin was doing.  You're right. After enabling that plugin, it did "just work."

Thanks!

**Comment by deadtrickster** [comment]
Glad it's working! I'll add this plugin to the README later.
