### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by uschtwill** [deadtrickster/prometheus_rabbitmq_exporter#6]
So, by default at `/api/metrics/`I see a very limited number of metrics, all describing the state of the system in VERY technical terms. Surely I can access metrics like `message count per queue` and such as well? 

Looking at [this](https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_5/priv/www/doc/stats.html) I am pretty confident I should be able to do that, but I can't for the life of me figure out how! 

Could you add an example or two to the readme?

**Comment by deadtrickster** [comment]
Hey!

You want to add more metrics?

**Comment by uschtwill** [comment]
Yes. :)

**Comment by deadtrickster** [comment]
This can be quite tricky actually, What you see in the document you linked is the description of the HTTP interface. Since this collector is more low-lever the usual process for adding a metric is to reverse back from http endpoint of RabbitMQ management plugin to statistics models internals. You can find how I'm doing this in the code. 

Now the question is what you really need and how. Lets start by figuring out what additional metrics you actually want. Also bear in mind you don't need *_rate metrics. Prometheus can calculate them for you.

**Comment by uschtwill** [comment]
Alright, I now just ended up using https://github.com/kbudde/rabbitmq_exporter, which achieves my purpose quite alright. Thanks though!

**Comment by deadtrickster** [comment]
Cool! While my exporter may lag behind in terms of metrics variety (I'm concentrated now on Erlang prometheus client itself) it also exports Eralng VM metrics. Anyway, glad you found what works for you.
